apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: apache_base
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hostvol
          mountPath: /var/www/html/
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      volumes:
      - name: hostvol
        hostPath:
          path: /home/surya/DockerKubernetes/src/
